# Generated by Django 5.1.1 on 2024-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/images/'),
        ),
    ]
