# Generated by Django 5.1.3 on 2024-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Law', 'Faculty of Law'), ('Commerce and Accountancy', 'Faculty of Commerce and Accountancy'), ('Political Science', 'Faculty of Political Science'), ('Economics', 'Faculty of Economics'), ('Social Administration', 'Faculty of Social Administration'), ('Liberal Arts', 'Faculty of Liberal Arts'), ('Journalism and Mass Communication', 'Faculty of Journalism and Mass Communication'), ('Sociology and Anthropology', 'Faculty of Sociology and Anthropology'), ('Science and Technology', 'Faculty of Science and Technology'), ('Engineering', 'Faculty of Engineering'), ('Medicine', 'Faculty of Medicine'), ('Public Health', 'Faculty of Public Health'), ('Allied Health Sciences', 'Faculty of Allied Health Sciences'), ('Nursing', 'Faculty of Nursing'), ('Architecture and Planning', 'Faculty of Architecture and Planning'), ('Fine and Applied Arts', 'Faculty of Fine and Applied Arts'), ('Learning Sciences and Education', 'Faculty of Learning Sciences and Education'), ('Innovation in Social Sciences', 'Faculty of Innovation in Social Sciences'), ('Pridi Banomyong International College', 'Pridi Banomyong International College'), ('College of Interdisciplinary Studies', 'College of Interdisciplinary Studies'), ('School of Global Studies', 'School of Global Studies'), ('Chulabhorn International College of Medicine', 'Chulabhorn International College of Medicine'), ('College of Innovation', 'College of Innovation'), ('Sirindhorn International Institute of Technology', 'Sirindhorn International Institute of Technology')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default_profile_picture.png', null=True, upload_to='profile_picture/'),
        ),
    ]
