# Generated by Django 5.1.3 on 2024-12-15 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_review', '0002_dormitory_remove_coursereview_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('established_date', models.DateField()),
                ('color', models.CharField(max_length=7)),
                ('logo', models.ImageField(upload_to='faculty_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='DormReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_or_video', models.FileField(blank=True, null=True, upload_to='review_media/')),
                ('anonymous', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tu_review.dormitory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tu_review.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('course_type', models.CharField(choices=[('core', 'วิชาเฉพาะ'), ('gen_ed', 'วิชาศึกษาทั่วไป'), ('elective', 'วิชาเลือกเสรี')], max_length=10)),
                ('interest', models.IntegerField()),
                ('practical_use', models.IntegerField()),
                ('future_use', models.IntegerField()),
                ('instructor_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tu_review.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
