# Generated by Django 5.1.3 on 2024-12-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tu_review', '0004_restaurant_alter_studyreview_semester_menuitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='res_name',
            new_name='name',
        ),
    ]
