# Generated by Django 5.1.3 on 2024-12-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tu_review', '0007_restaurant_image_alter_studyreview_future_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormreview',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='dormreview',
            name='image_or_video',
        ),
        migrations.DeleteModel(
            name='DormRequest',
        ),
    ]
