# Generated by Django 5.1.1 on 2024-12-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_review', '0008_remove_dormreview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dorms/images/'),
        ),
    ]
